### ISSUE TITLE
Add ANSI Color Output to Hello World Program

### ISSUE THREAD

**Issue by PerArneng** [L1NX09/hello-world#1]
**Description**
Our current Hello World program outputs plain text without any color. To enhance the visibility and user experience, I propose we implement ANSI color codes to add color to the output. This will make the program outputs more visually appealing and easier to read in terminals that support color.

**Expected Behavior**
When the program runs, it should display "Hello, World!" in green text. The implementation should use ANSI escape codes to set the text color.

**Current Behavior**
The program currently displays the text "Hello, World!" in the default terminal color without any ANSI color formatting.

**Possible Solution**
The output line in the program can be modified to include ANSI escape codes for coloring. For example:
`echo -e "\033[0;32mHello, World!\033[0m"`

@L1NX09  ⭐️

**Comment by linusarneng** [comment]
I dont have time.
